version: '3.8'
services:
  ratings:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://ratings:ratingspass@mongodb:27017   
      MONGO_DB_NAME: ratings   
  mongodb:
    image: bitnami/mongodb:4.4.2-debian-10-r0
    volumes:
      - "./databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: rootpass
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: ratingspass
      MONGODB_DATABASE: ratings